FROM python:3.8-slim-buster as main
RUN mkdir /app
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY . .
RUN ls -al

FROM cytopia/pylint:latest
COPY --from=main /app .
CMD [ "pylint". "." ]

FROM python:3.8-slim-buster
RUN mkdir /app
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY . .
USER user
EXPOSE 5000
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]


